services:
  - type: web
    name: synthrun-mail
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: ALLOWED_DOMAIN
        value: synthrun.site
      - key: FROM_NAME
        value: Synthrun Mail
      - key: FROM_NAME_TEMPLATE
        value: "Synthrun Mail"
      - key: SENDER_ADDRESS
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      - key: ALLOWED_BYPASS
        value: "0"
